map_server:
  ros__parameters:
    yaml_filename: "carter_warehouse_navigation.yaml"
    topic_name: "map"
    frame_id: "map"
    service_introspection_mode: "disabled"

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    service_introspection_mode: "disabled"